In [1]:
import pandas as pd

In [2]:
ICA = pd.read_excel(r"C:\Users\egonz\Desktop\LIMPIAR DATA/ICA_FINALIZADO.xlsx")
ICA["Region"] = "ICA"
Region = ICA["Region"]
ICA.drop(labels = "Region", axis=1, inplace = True)
ICA.insert(0, "Region", Region)
ICA.columns= ["Region","District","Place","4_6_years_men","4_6_years_women"
,"4_6_years_total","6_14_years_men","6_14_years_women","6_14_years_total","man_read","women_read","total_read","men_not_read","women_not_read","total_not_read","man_write","women_write","total_write","men_not_write","women_not_write","total_not_write","instruction_men","instruction_women","instruction_total","no_instruction_men","no_instruction_women","no_instruction_total","finished_instr_men","finished_instr_women","finished_instr_total","not_finished_instr_men","not_finished_instr_women","not_finished_instr_total","peruvian_men"
 , "peruvian_women", "foreign_men", "foreign_women", "whites", "natives", "mestizos" , "blacks"]

In [3]:
ICA["District"] =ICA["District"].str.upper()
ICA["Place"] = ICA["Place"].str.upper()

In [4]:
ICA["Place"] = ICA["Place"].str.strip()
# Find errors with string = Total
errors = ICA.loc[ICA["Place"]=="TOTAL"]
error_list = errors.index.tolist()

In [5]:
ICA_clean = ICA.drop(ICA.index[error_list])

In [6]:
ICA_clean = ICA_clean.drop([0, 1, 2],axis=0)

In [7]:
ICA_clean = ICA_clean.reset_index()
ICA_clean

,index,Region,District,Place,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,...,not_finished_instr_women,not_finished_instr_total,peruvian_men,peruvian_women,foreign_men,foreign_women,whites,natives,mestizos,blacks
0,3,ICA,ICA,CD.ICA,83,107,190,538,569,1107,...,649,1221,621,676,0,0,289,617,357,34
1,4,ICA,ICA,P.COMATRANA,7,7,14,32,24,56,...,31,70,39,31,0,0,0,70,0,0
2,5,ICA,ICA,CACHICHE,4,8,12,25,16,41,...,24,53,29,24,0,0,1,52,0,0
3,6,ICA,ICA,SAN JOAQUIN (CHANCHAJAYA),8,7,15,56,23,79,...,30,94,64,30,0,0,0,39,55,0
4,7,ICA,ICA,TINGUIÑA,10,12,22,65,48,113,...,58,133,75,60,0,0,0,72,32,1
5,8,ICA,ICA,PARCONA,14,5,19,37,26,63,...,31,81,51,31,0,0,0,80,0,2
6,9,ICA,ICA,ORONGO,22,13,35,84,62,146,...,74,179,106,75,0,0,4,90,87,0
7,10,ICA,ICA,SARAJA,10,13,23,44,38,82,...,51,105,54,51,0,0,0,61,37,7
8,12,ICA,SAN JUAN BAUSTISTA,P.SAN JUAN BAUTISTA,2,3,5,33,40,73,...,43,76,35,43,0,0,10,51,0,17
9,13,ICA,SAN JUAN BAUSTISTA,A.GUADALUPE,3,5,8,63,64,127,...,69,135,66,69,0,0,9,120,6,0
10,14,ICA,SAN JUAN BAUSTISTA,COLLASOH,0,0,0,25,25,50,...,25,50,25,25,0,0,0,50,0,0
11,15,ICA,SAN JUAN BAUSTISTA,CARMEN ALTO,7,9,16,57,42,99,...,51,115,64,51,0,0,0,63,47,5
12,16,ICA,SAN JUAN BAUSTISTA,C.CAMINO DE REYES,0,1,1,44,30,74,...,31,75,44,31,0,0,7,62,6,0
13,17,ICA,SAN JUAN BAUSTISTA,OLIVO,7,2,9,13,9,22,...,11,31,20,11,0,0,0,12,18,1
14,18,ICA,SAN JUAN BAUSTISTA,H.SULTANJALLA,2,2,4,48,28,76,...,30,80,50,30,0,0,3,61,12,4
15,20,ICA,PUEBLO NUEVO,P.PUEBLO NUEVO,7,5,12,82,41,123,...,46,135,89,46,0,0,0,134,0,1
16,21,ICA,PUEBLO NUEVO,A.TALLAMANA,25,5,30,60,38,98,...,43,128,85,43,0,0,11,117,0,0
17,23,ICA,NAZCA,V.NAZCA,3,1,4,36,39,75,...,35,66,39,40,0,0,14,3,60,2
18,25,ICA,PISCO,P.PISCO,121,115,236,359,431,790,...,481,914,480,546,0,0,152,292,25,547
19,26,ICA,PISCO,H.CAUCATO,1,0,1,29,12,41,...,12,42,30,12,0,0,0,27,0,15
20,27,ICA,PISCO,C.SAN MIGUEL,9,15,24,79,67,146,...,82,170,88,82,0,0,0,80,63,27
21,28,ICA,PISCO,PLAYA DEL PUERTO,23,25,48,105,115,220,...,132,255,128,140,0,0,57,92,91,28
22,29,ICA,PISCO,C.SAN ANDRÉS,13,15,28,53,54,107,...,69,133,66,69,0,0,5,128,0,2
23,31,ICA,HUMAY,P.HUMAY,4,8,12,56,38,94,...,46,103,60,46,0,0,18,58,25,5
24,32,ICA,HUMAY,CHUNCHANGA,12,13,25,50,30,80,...,43,105,62,43,0,0,3,70,20,12
25,34,ICA,HUÁNCANO,P.HUÁNCANO,7,4,11,35,27,62,...,31,66,42,31,0,0,19,34,19,1
26,36,ICA,CHINCHA ALTA,P.CHINCHA ALTA,103,115,218,478,496,974,...,507,955,551,611,0,0,224,603,261,104
27,37,ICA,CHINCHA ALTA,ÑOCO BAJO,5,3,8,170,160,330,...,155,315,175,163,0,0,0,338,0,0
28,38,ICA,CHINCHA ALTA,CONDORILLO,45,45,90,170,155,325,...,200,411,215,200,0,0,0,409,0,6
29,39,ICA,CHINCHA ALTA,ÑOCO ALTO,2,0,2,158,104,262,...,104,262,160,104,0,0,3,259,0,2
30,40,ICA,CHINCHA ALTA,PILPA,0,0,0,214,0,214,...,0,192,214,0,0,0,1,213,0,0
31,41,ICA,CHINCHA ALTA,ACEQUIA GRANDE,27,28,55,119,92,211,...,116,251,264,0,0,0,0,264,0,0
32,42,ICA,CHINCHA ALTA,C.SUNAMPE,20,35,55,135,106,241,...,133,262,155,141,0,0,1,268,23,4
33,44,ICA,CHINCHA BAJA,P.CHINCHA BAJA,42,59,101,319,344,663,...,394,742,361,403,0,0,52,394,201,117
34,45,ICA,CHINCHA BAJA,H.HOJA REDONDA,2,0,2,23,0,23,...,0,25,25,0,0,0,0,20,5,0
35,47,ICA,TAMBO DE MORA,P.TAMBO DE MORA,15,18,33,104,106,210,...,121,236,119,124,0,0,49,21,127,46

In [8]:
a = ICA_clean.drop("index", axis=1)
a.dtypes

Region                      object
District                    object
Place                       object
4_6_years_men               object
4_6_years_women             object
4_6_years_total             object
6_14_years_men              object
6_14_years_women            object
6_14_years_total            object
man_read                    object
women_read                  object
total_read                  object
men_not_read                object
women_not_read              object
total_not_read              object
man_write                   object
women_write                 object
total_write                 object
men_not_write               object
women_not_write             object
total_not_write             object
instruction_men             object
instruction_women           object
instruction_total           object
no_instruction_men          object
no_instruction_women        object
no_instruction_total        object
finished_instr_men          object
finished_instr_women        object
finished_instr_total        object
not_finished_instr_men      object
not_finished_instr_women    object
not_finished_instr_total    object
peruvian_men                object
peruvian_women              object
foreign_men                 object
foreign_women               object
whites                      object
natives                     object
mestizos                    object
blacks                      object
dtype: object

In [9]:

a12= a.infer_objects()
a12.dtypes

Region                      object
District                    object
Place                       object
4_6_years_men                int64
4_6_years_women              int64
4_6_years_total              int64
6_14_years_men               int64
6_14_years_women             int64
6_14_years_total             int64
man_read                     int64
women_read                   int64
total_read                   int64
men_not_read                 int64
women_not_read               int64
total_not_read               int64
man_write                    int64
women_write                  int64
total_write                  int64
men_not_write                int64
women_not_write              int64
total_not_write              int64
instruction_men              int64
instruction_women            int64
instruction_total            int64
no_instruction_men           int64
no_instruction_women         int64
no_instruction_total         int64
finished_instr_men           int64
finished_instr_women         int64
finished_instr_total         int64
not_finished_instr_men       int64
not_finished_instr_women     int64
not_finished_instr_total     int64
peruvian_men                 int64
peruvian_women               int64
foreign_men                  int64
foreign_women                int64
whites                       int64
natives                      int64
mestizos                     int64
blacks                       int64
dtype: object

In [10]:
errors1 =a12.loc[a12["Place"]=="TOTAL"]
errors1

Empty DataFrame
Columns: [Region, District, Place, 4_6_years_men, 4_6_years_women, 4_6_years_total, 6_14_years_men, 6_14_years_women, 6_14_years_total, man_read, women_read, total_read, men_not_read, women_not_read, total_not_read, man_write, women_write, total_write, men_not_write, women_not_write, total_not_write, instruction_men, instruction_women, instruction_total, no_instruction_men, no_instruction_women, no_instruction_total, finished_instr_men, finished_instr_women, finished_instr_total, not_finished_instr_men, not_finished_instr_women, not_finished_instr_total, peruvian_men, peruvian_women, foreign_men, foreign_women, whites, natives, mestizos, blacks]
Index: []

[0 rows x 41 columns]

In [12]:
Code1= a12.to_excel("Region_Ica.xlsx")
Code1